kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
name: api-ns-user-view
namespace: api-ns
subjects:
- kind: ServiceAccount
name: api-ns-user
namespace: api-dev
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: api-ns-user-view-access