apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web-ns
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryylj7757.azurecr.io/tripinsights/tripviewer:latest
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.default.svc.cluster.local:8080"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service.default.svc.cluster.local:8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"