apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryylj7757.azurecr.io/tripinsights/tripviewer:latest
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: 
          name: USERPROFILE_API_ENDPOINT
          value: "sqladminyLj7757"
        