apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api-ns
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryylj7757.azurecr.io/tripinsights/userprofile:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: keyvault-sp
          options:
            keyvaultname: "Team3KeyVault21"
            keyvaultobjectnames: "sql-user;sql-password;sql-server-name"
            keyvaultobjecttypes: "secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"
            resourcegroup: "teamResources"
            subscriptionid: 89eb5de7-be0a-4488-8b3a-a78358b2d3bb
            tenantid: b6995c8f-8cfc-4e17-8898-892cb00eb98a
          resources:
          limits:
            memory: "128Mi"
            cpu: "500m"