apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api-ns
  labels:
    app: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryylj7757.azurecr.io/tripinsights/user-java:latest
        ports:
        - containerPort: 80
          volumeMounts:
          - name: keyvault
            mountPath: /secrets
            readOnly: true
        volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: keyvault-sp
          options:
            keyvaultname: "Team3KeyVault21"
            keyvaultobjectnames: "sql-user;sql-password;sql-server-name"
            keyvaultobjecttypes: "secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"
            resourcegroup: "teamResources"
            subscriptionid: 89eb5de7-be0a-4488-8b3a-a78358b2d3bb
            tenantid: b6995c8f-8cfc-4e17-8898-892cb00eb98a