apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sql 
  namespace: api-ns
spec:
  vault:
    name: Team3KeyVault21 # 1. name of key vault
    object:
    - name: sql-user # 2. name of the akv object
      type: secret # 3. akv object type
    - name: sql-password # 2. name of the akv object
      type: secret # 3. akv object type
    - name: sql-server-name
      type: secret
  output: 
    secret: 
    - name: SQL_USER # 4. kubernetes secret name
      dataKey: sql-user # 5. key to store object value in kubernetes secret
    - name: SQL_PASSWORD # 4. kubernetes secret name
      dataKey: sql-password # 5. key to store object value in kubernetes secret
    - name: SQL_SERVER
      dataKey: sql-server-name